# This is the configuration used to check the rubocop source code.

require: rubocop/cop/internal_affairs

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.4.1

Documentation:
  Enabled: false

# Naming/PredicateName:
  # Method define macros for dynamically generated method.
  # MethodDefineMacros:
  #   - define_method
  #   - define_singleton_method
  #   - def_node_matcher

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Performance/Caller:
  Exclude:
    - spec/rubocop/cop/performance/caller_spec.rb
